### ISSUE TITLE
Failed to load schema

### ISSUE THREAD

**Issue by harichen** [Glosseta/storedat-api-starter-template#7]
run command：“yarn generate-gq” report an error：
```
Failed to load schema from https://perma.storedat.io/api/graphql:
      Could not obtain introspection result, received the following as response;
      undefined
      GraphQLError: Could not obtain introspection result, received the following as response;
      undefined
      at createGraphQLError (/Users/chenjianhong/Documents/GitHub/storedat-api-starter-template/node_modules/@graphql-tools/utils/cjs/errors.js:9:12)
      at getSchemaFromIntrospection (/Users/chenjianhong/Documents/GitHub/storedat-api-starter-template/node_modules/@graphql-tools/wrap/cjs/introspect.js:21:42)
      at /Users/chenjianhong/Documents/GitHub/storedat-api-starter-template/node_modules/@graphql-tools/wrap/cjs/introspect.js:36:32
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async UrlLoader.load (/Users/chenjianhong/Documents/GitHub/storedat-api-starter-template/node_modules/@graphql-tools/url-loader/cjs/index.js:211:29)
      at async /Users/chenjianhong/Documents/GitHub/storedat-api-starter-template/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:17:39
      at async Promise.all (index 5)
      at async loadFile (/Users/chenjianhong/Documents/GitHub/storedat-api-starter-template/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:15:9)
      at async /Users/chenjianhong/Documents/GitHub/storedat-api-starter-template/node_modules/@graphql-tools/load/cjs/load-typedefs/collect-sources.js:229:25
      GraphQL Code Generator supports:
      - ES Modules and CommonJS exports (export as default or named export "schema")
      - Introspection JSON File
      - URL of GraphQL endpoint
      - Multiple files with type definitions (glob expression)
      - String in config file
      Try to use one of above options and run codegen again.
◼ Load GraphQL documents
◼ Generate
```
codegen.yml：
`generates:
  ./src/resources/graphql/types/storedat-gql-types.ts:
    schema: "https://perma.storedat.io/api/graphql"
    plugins:
      - typescript
      - typescript-operations`

**Comment by harichen** [comment]
I find the url:“https://perma.storedat.io/api/graphql” response 404
then I use "http://localhost:3000" replace “https://perma.storedat.io/api/graphql” 
run the command：“yarn generate-gq”
This error cannot be resolved.

**Comment by narbs91** [comment]
Hi @harichen excellent find!  The issue is with the url being incorrect, it should be `https://perma.storedat.io/api/v1/graphql`

I have since fixed it with https://github.com/Glosseta/storedat-api-starter-template/pull/8

Please pull the latest code and let me know if you have any further issues
